services:
  t-db:
    image: postgres:16
    container_name: jl-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: jl_db
      POSTGRES_USER: jl_user
      POSTGRES_PASSWORD: jl_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - jl-net-t

  t-backend:
    build: ./backend
    container_name: jl-backend-test
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - t-db
    networks:
      - jl-net-t
    ports:
      - "3000:3000"

networks:
  jl-net-t:
    driver: bridge
